language: cpp
os: linux
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - sudo apt-get install gfortran -y
  - type gfortran
jobs:
  include:
    - stage: build-and-test
      install: autoreconf -i && ./configure && make -j8 
      script: make check -j8 && cat test/test_results.txt
    - 
      install: mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$PWD .. && make -j8 install
      script: ./test.sh
